### PR TITLE
instance Eq RSAError

### PR DESCRIPTION
**Pull request by dmalikov**

### CODE REVIEW

**Comment by acw** [comment]
Thanks!

**Comment by dmalikov** [comment]
Do you have any plans to minor-bump the package's version on hackage by any chance?

**Comment by acw** [comment]
I hadn't but I'm guessing you'd like one, so I'll do it shortly. :)

**Comment by acw** [comment]
RSA-2.2.0 is up on Hackage.

**Comment by dmalikov** [comment]
@acw thank you!

**Pull request merged**
